name: release

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      with:
        release-type: ruby
        package-name: sqlit3-ext-closure
        bump-minor-pre-major: true
        version-file: "lib/sqlite3-ext-closure/version.rb"


